version: '3'

services:
  web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8002:8000"
        environment:
            - USE_S3=TRUE
            - AWS_ACCESS_KEY_ID=AKIAQ3EGSHFKZLIO3SGE
            - AWS_SECRET_ACCESS_KEY=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
            - AWS_STORAGE_BUCKET_NAME=django-media-cumn