# Generated by Django 5.0.3 on 2024-03-15 10:06

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idBd', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('modelImage', models.ImageField(blank=True, null=True, upload_to=api.models.generate_shield_dirname)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='fotoPerfil',
            field=models.ImageField(blank=True, default='fotosPerfil/default.jpg', null=True, upload_to=api.models.generate_image_dirname),
        ),
    ]
