# Generated by Django 5.0.3 on 2024-03-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipo_alter_user_fotoperfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='modelImage',
            new_name='fotoEscudo',
        ),
    ]
