# Generated by Django 5.0.3 on 2024-03-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_modelimage_equipo_fotoescudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipoFavorito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipo'),
        ),
    ]
