# Generated by Django 5.0.3 on 2024-03-25 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_equipofavorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idBd', models.AutoField(primary_key=True, serialize=False)),
                ('estadio', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('jornada', models.IntegerField()),
                ('fecha', models.DateField()),
                ('golesLocal', models.IntegerField()),
                ('golesVisitante', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('minuto', models.IntegerField()),
                ('equipoLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipoLocal', to='api.equipo')),
                ('equipoVisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipoVisitante', to='api.equipo')),
            ],
        ),
    ]
