# Generated by Django 5.0.3 on 2024-04-01 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idBd', models.AutoField(primary_key=True, serialize=False)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to=settings.AUTH_USER_MODEL)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
