# Generated by Django 5.0.3 on 2024-04-01 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seguido'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguido',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
